# -*- mode: ruby -*-
# vi: set ft=ruby :

home_dir = ENV['HOME']
docker_hdd= home_dir + '/VirtualBox HDDs/{{ VADO_NAME }}/docker_hdd.vdi'
pubkey = File.read("{{ VADO_SSH_KEY_FILE }}.pub")

$script_always = <<SCRIPT
set -e
echo Running 'always' provisioning...
if sudo file -Ls /dev/sdb | grep -q ext4; then
  echo 'No mkfs.ext4 needed';
else
  sudo mkfs.ext4 /dev/sdb;
fi

if mount | grep -qs "/var/lib/docker"; then
  echo 'Mount exists'
else
  echo 'Mounting /var/lib/docker to secondary disk'
  sudo mkdir -p /var/lib/docker
  sudo mount -t ext4 /dev/sdb /var/lib/docker
fi

echo 'Restarting docker daemon..'
sudo service docker restart

echo 'Done.'
SCRIPT

Vagrant.configure(2) do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "{{ VADO_IP }}"

  # Mac OS X

  config.vm.synced_folder home_dir, home_dir, type: "nfs", mount_options: ['actimeo=2']

  # Name in Vagrant
  config.vm.define "{{ VADO_NAME }}" do |vado_name|
  end

  config.vm.provider "virtualbox" do |vb|
     # Name in VBoxManage
     vb.name = "{{ VADO_NAME }}"
     vb.memory = {{ VADO_RAM }}
     unless File.exist?(docker_hdd)
         vb.customize ['createhd', '--filename', docker_hdd, '--size', 50 * 1024]
     end
     vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', docker_hdd]
  end

  # we need a newline after vagrant default key
  config.vm.provision "shell", inline: "echo '' >> .ssh/authorized_keys"
  config.vm.provision "shell", inline: "echo '" + pubkey + "' >> .ssh/authorized_keys"

  config.vm.provision "shell", run: "always", inline: $script_always

end
